### ISSUE TITLE
Suggestion Discussion

### ISSUE THREAD

**Issue by MrAugu** [Tetracyl/CoronaCord#2]
This issue resembles all suggestions we are aware of.

- [ ] World-Wide Graph
- [ ] Real-Time Feeds
- [ ] World Top Graph
- [ ] Support for Continents/Regions
- [ ] Enhance World Top List (Make it fancy.)
- [ ] Aliases for Commands
- [ ] Sync Data from WorldOMetrics More Frequently
- [ ] Multi-Language Support
- [ ] Custom Prefix
- [ ] Ignored Channels

**Comment by 3eif** [comment]
We will not be adding any more features to the bot. If you encounter a bug please make a new issue so that we can fix it. Thank you for understanding.
